
SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE IF NOT EXISTS evtest CHARACTER SET utf8;

GRANT ALL PRIVILEGES ON evtest.* TO 'evtestuser'@localhost IDENTIFIED BY 'evtestpass' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON evtest.* TO 'evtestuser'@'%' IDENTIFIED BY 'evtestpass' WITH GRANT OPTION;
FLUSH PRIVILEGES;
